/**
 * Programmatically drafted editorial teachings.
 * ALL entries are marked `draft` and must not be labeled educator-reviewed
 * until a qualified rabbi or Jewish educator reviews them.
 */
import type { Teaching, Theme } from "./types";
import { inferSourceCategory } from "./source-category";

type DraftSeed = {
  id: string;
  theme: Theme;
  themeLabel: string;
  canonical: string;
  url?: string;
  text: string;
  context: string;
  application: string;
  takeaway: string;
  question: string;
  acknowledgment: string;
  keywords: string[];
};

function draft(seed: DraftSeed): Teaching {
  const category = inferSourceCategory(seed.canonical);
  return {
    id: seed.id,
    theme: seed.theme,
    themeLabel: seed.themeLabel,
    sources: [
      {
        canonical: seed.canonical,
        citationLabel: seed.canonical,
        url: seed.url,
        category,
      },
    ],
    textKind: "paraphrase",
    text: seed.text,
    historicalContext: seed.context,
    modernApplication: `Modern application (not source language): ${seed.application}`,
    takeaway: seed.takeaway,
    reflectionQuestion: seed.question,
    acknowledgment: seed.acknowledgment,
    viewpoint: "Draft editorial lens awaiting educator review",
    keywords: seed.keywords,
    reviewStatus: "draft",
  };
}

const SEEDS: DraftSeed[] = [
  // patience (+3)
  {
    id: "patience-exodus-34-6",
    theme: "patience",
    themeLabel: "Patience",
    canonical: "Exodus 34:6",
    url: "https://www.sefaria.org/Exodus.34.6",
    text: "In the divine attributes proclaimed to Moses, God is described as slow to anger — a classical image of patience held together with compassion and truth.",
    context: "Exodus 34 lists attributes that later Jewish liturgy and ethics treat as a model for human character.",
    application: "Slowing anger can create space for truth and compassion to appear.",
    takeaway: "When anger rises, delay the reaction long enough for one clearer word.",
    question: "What would “slow to anger” look like in your next difficult moment?",
    acknowledgment: "Waiting before reacting is its own kind of strength.",
    keywords: ["slow to anger", "patience", "anger", "temper", "wait"],
  },
  {
    id: "patience-numbers-12",
    theme: "patience",
    themeLabel: "Patience",
    canonical: "Numbers 12:3",
    url: "https://www.sefaria.org/Numbers.12.3",
    text: "Numbers describes Moses as very humble — a character note often read alongside patience under criticism.",
    context: "Numbers 12 narrates conflict and criticism within leadership; humility appears as a narrative attribute of Moses.",
    application: "Humility can soften the urge to retaliate when we feel misread.",
    takeaway: "Ask whether defending your image is more urgent than understanding the criticism.",
    question: "Where might humility make patience easier?",
    acknowledgment: "Criticism stings — patience can still be a choice.",
    keywords: ["humble", "criticism", "patience", "leadership conflict"],
  },
  {
    id: "patience-deut-8",
    theme: "patience",
    themeLabel: "Patience",
    canonical: "Deuteronomy 8:2",
    url: "https://www.sefaria.org/Deuteronomy.8.2",
    text: "Deuteronomy recalls the wilderness as a long testing path meant to reveal what is in the heart.",
    context: "Moses interprets the wilderness years as formative, not merely punitive.",
    application: "Long seasons can uncover character; patience includes staying with the process.",
    takeaway: "Name one lesson this waiting period may be teaching you.",
    question: "What is this season revealing about what you value?",
    acknowledgment: "Long waits can feel like wilderness.",
    keywords: ["wilderness", "waiting", "test", "patience", "journey"],
  },
  // repair (+4)
  {
    id: "repair-lev-5-5",
    theme: "repair",
    themeLabel: "Repair and apology",
    canonical: "Leviticus 5:5",
    url: "https://www.sefaria.org/Leviticus.5.5",
    text: "Leviticus links certain wrongs with confession — speaking the fault as part of repair.",
    context: "Confession in sacrificial contexts is a ritualized naming of wrongdoing, not a modern therapy script.",
    application: "Naming harm plainly remains a first step in many repair processes.",
    takeaway: "Say the specific wrong without minimizing it.",
    question: "What needs to be named out loud for repair to begin?",
    acknowledgment: "Naming a wrong is hard — and often necessary.",
    keywords: ["confess", "confession", "admit", "repair", "wrong"],
  },
  {
    id: "repair-gen-50-17",
    theme: "repair",
    themeLabel: "Repair and apology",
    canonical: "Genesis 50:17-21",
    url: "https://www.sefaria.org/Genesis.50.17",
    text: "Joseph’s brothers seek forgiveness after their father’s death; Joseph reframes the past without denying the harm.",
    context: "Genesis closes Joseph’s story with fear, request for forgiveness, and a complex reconciliation.",
    application: "Repair can include honesty about harm and a refusal to perpetuate the cycle.",
    takeaway: "Ask what reassurance the harmed person needs that the pattern will not continue.",
    question: "What would make repair feel trustworthy, not just verbal?",
    acknowledgment: "Old harms can resurface when stakes feel high.",
    keywords: ["forgive", "forgiveness", "joseph", "brothers", "repair"],
  },
  {
    id: "repair-exodus-22",
    theme: "repair",
    themeLabel: "Repair and apology",
    canonical: "Exodus 22:4",
    url: "https://www.sefaria.org/Exodus.22.4",
    text: "Exodus describes restitution when someone’s animal grazes in another’s field — harm followed by making good.",
    context: "Civil law in Exodus often pairs damage with concrete compensation.",
    application: "Sometimes repair is practical restoration, not only emotional language.",
    takeaway: "Offer a concrete make-good where one is possible.",
    question: "What tangible restoration would match the harm?",
    acknowledgment: "Words help — and so can making things right in practice.",
    keywords: ["restitution", "restore", "damage", "amends", "repair"],
  },
  {
    id: "repair-num-5-6",
    theme: "repair",
    themeLabel: "Repair and apology",
    canonical: "Numbers 5:6-7",
    url: "https://www.sefaria.org/Numbers.5.6",
    text: "Numbers connects wronging another person with confession and restoring the principal, plus an added fifth.",
    context: "This passage concerns interpersonal wrongs framed within a ritual-legal setting.",
    application: "Repair may include both confession and measurable restoration.",
    takeaway: "Pair apology with a restoration that costs you something real.",
    question: "What would a “plus a fifth” spirit look like in your repair?",
    acknowledgment: "True repair often asks for more than the minimum.",
    keywords: ["restore", "confession", "fifth", "wrong another", "repair"],
  },
  // relationships (+3)
  {
    id: "relationships-lev-19-17",
    theme: "relationships",
    themeLabel: "Difficult relationships",
    canonical: "Leviticus 19:17",
    url: "https://www.sefaria.org/Leviticus.19.17",
    text: "Leviticus teaches not to hate one’s fellow in one’s heart, and to rebuke rather than bear sin because of them.",
    context: "This verse sits near other Holiness Code ethics about speech, revenge, and neighbor-love.",
    application: "Honest, careful rebuke can be more loving than silent resentment — when done without humiliation.",
    takeaway: "If resentment is growing, consider a respectful direct conversation.",
    question: "What needs saying — and how can it be said without contempt?",
    acknowledgment: "Unspoken resentment can weigh more than a hard conversation.",
    keywords: ["rebuke", "hate", "resentment", "confrontation", "fellow"],
  },
  {
    id: "relationships-gen-13",
    theme: "relationships",
    themeLabel: "Difficult relationships",
    canonical: "Genesis 13:8-9",
    url: "https://www.sefaria.org/Genesis.13.8",
    text: "Abram seeks to end strife with Lot by offering space and choice rather than escalating the quarrel.",
    context: "A narrative of conflict over resources between kin; Abram’s de-escalation is descriptive, not a universal rule.",
    application: "Sometimes relationships heal when someone creates room instead of winning the argument.",
    takeaway: "Ask whether generosity of space could lower the temperature.",
    question: "Where could you offer space without abandoning what matters?",
    acknowledgment: "Even close relationships can fill with strife.",
    keywords: ["strife", "quarrel", "family conflict", "space", "lot"],
  },
  {
    id: "relationships-deut-24-10",
    theme: "relationships",
    themeLabel: "Difficult relationships",
    canonical: "Deuteronomy 24:10-13",
    url: "https://www.sefaria.org/Deuteronomy.24.10",
    text: "Deuteronomy protects a borrower’s dignity in the taking of a pledge — even creditors must respect personhood.",
    context: "Debt law here limits domination and preserves dignity in unequal relationships.",
    application: "Power imbalances call for extra care about dignity.",
    takeaway: "In uneven dynamics, protect the other person’s dignity as carefully as your interest.",
    question: "Where do you hold power — and how is dignity protected there?",
    acknowledgment: "Unequal relationships need extra gentleness.",
    keywords: ["dignity", "power", "debt", "respect", "relationship"],
  },
  // leadership (+4)
  {
    id: "leadership-exodus-18",
    theme: "leadership",
    themeLabel: "Leadership",
    canonical: "Exodus 18:17-23",
    url: "https://www.sefaria.org/Exodus.18.17",
    text: "Jethro advises Moses that carrying every case alone is not good — leadership needs shared structure.",
    context: "Jethro’s counsel introduces delegated judging and sustainable leadership.",
    application: "Good leaders share load and build systems rather than becoming bottlenecks.",
    takeaway: "Delegate one responsibility you have been carrying alone.",
    question: "What are you holding that others could help carry?",
    acknowledgment: "Carrying everything alone is not always faithfulness.",
    keywords: ["delegate", "leadership", "jethro", "burnout", "share load"],
  },
  {
    id: "leadership-deut-17",
    theme: "leadership",
    themeLabel: "Leadership",
    canonical: "Deuteronomy 17:18-20",
    url: "https://www.sefaria.org/Deuteronomy.17.18",
    text: "A king is told to write and read the Teaching so that his heart not be lifted above his fellows.",
    context: "Torah’s “law of the king” constrains royal power with study and humility.",
    application: "Authority needs ongoing learning and resistance to ego inflation.",
    takeaway: "Return to a text or mentor that keeps your ego in check.",
    question: "What practice keeps your heart from rising above others?",
    acknowledgment: "Power can quietly lift the heart.",
    keywords: ["king", "authority", "ego", "humility", "leadership"],
  },
  {
    id: "leadership-num-11",
    theme: "leadership",
    themeLabel: "Leadership",
    canonical: "Numbers 11:16-17",
    url: "https://www.sefaria.org/Numbers.11.16",
    text: "God tells Moses to gather seventy elders to share the spirit of responsibility.",
    context: "Leadership crisis in the wilderness leads to distributed spirit and shared burden.",
    application: "Shared leadership can be a spiritual as well as practical necessity.",
    takeaway: "Invite one trusted person into the decision you’ve been holding alone.",
    question: "Who could share this responsibility with integrity?",
    acknowledgment: "Some loads are too heavy for one set of shoulders.",
    keywords: ["elders", "shared leadership", "burden", "spirit", "team"],
  },
  {
    id: "leadership-exodus-3",
    theme: "leadership",
    themeLabel: "Leadership",
    canonical: "Exodus 3:11-12",
    url: "https://www.sefaria.org/Exodus.3.11",
    text: "Moses questions his adequacy for leadership; the response emphasizes presence more than self-confidence.",
    context: "The burning-bush call narrative includes reluctance and reassurance.",
    application: "Feeling unready does not always disqualify a responsible yes.",
    takeaway: "Separate “I feel inadequate” from “I will take the next faithful step.”",
    question: "What next step is yours even while you feel unready?",
    acknowledgment: "Doubt and calling can arrive together.",
    keywords: ["reluctant", "inadequate", "call", "leadership", "moses"],
  },
  // courage (+3)
  {
    id: "courage-deut-31-6",
    theme: "courage",
    themeLabel: "Courage",
    canonical: "Deuteronomy 31:6",
    url: "https://www.sefaria.org/Deuteronomy.31.6",
    text: "Israel is told to be strong and courageous, not to fear, because God goes with them.",
    context: "Moses prepares the people for transition into the land without him.",
    application: "Courage here is steadiness amid transition, supported by presence.",
    takeaway: "Name who or what accompanies you into the hard step.",
    question: "What companionship makes courage possible for you?",
    acknowledgment: "Transitions ask for courage even when the path is right.",
    keywords: ["be strong", "courage", "fear not", "transition"],
  },
  {
    id: "courage-exodus-14-13",
    theme: "courage",
    themeLabel: "Courage",
    canonical: "Exodus 14:13-14",
    url: "https://www.sefaria.org/Exodus.14.13",
    text: "At the sea, Moses tells the people not to fear and to stand firm — courage as composure under threat.",
    context: "Narrative of the Exodus at the Reed Sea; later midrash expands initiative (e.g., Nachshon).",
    application: "Sometimes courage is refusing panic long enough to see the next move.",
    takeaway: "When panic rises, plant your feet and breathe before deciding.",
    question: "What would standing firm look like without freezing?",
    acknowledgment: "Fear can be loud at the water’s edge.",
    keywords: ["fear not", "stand firm", "sea", "panic", "courage"],
  },
  {
    id: "courage-num-13-20",
    theme: "courage",
    themeLabel: "Courage",
    canonical: "Numbers 13:30",
    url: "https://www.sefaria.org/Numbers.13.30",
    text: "Caleb stills the people and insists they can go up — a minority report of courage against discouraging consensus.",
    context: "The spies’ report splits between fear and confidence; Caleb’s stance is contested leadership.",
    application: "Courage sometimes means speaking a hopeful truth against group anxiety.",
    takeaway: "If you hold a responsible hope, say it calmly once.",
    question: "Where are you needed as a steady voice rather than an echo?",
    acknowledgment: "Group fear can make courage lonely.",
    keywords: ["caleb", "spies", "courage", "hope", "majority"],
  },
  // gratitude (+4)
  {
    id: "gratitude-deut-8-10",
    theme: "gratitude",
    themeLabel: "Gratitude",
    canonical: "Deuteronomy 8:10",
    url: "https://www.sefaria.org/Deuteronomy.8.10",
    text: "Deuteronomy instructs that when you have eaten and are satisfied, you should bless.",
    context: "Blessing after satisfaction is a Torah practice of remembering the Source amid plenty.",
    application: "Gratitude is trained especially when we are full, not only when we are lacking.",
    takeaway: "After a meal or win today, pause for one explicit thank-you.",
    question: "What satisfaction have you rushed past without blessing?",
    acknowledgment: "Fullness can make us forgetful.",
    keywords: ["bless", "satisfied", "thank", "gratitude", "meal"],
  },
  {
    id: "gratitude-exodus-15-1",
    theme: "gratitude",
    themeLabel: "Gratitude",
    canonical: "Exodus 15:1-2",
    url: "https://www.sefaria.org/Exodus.15.1",
    text: "After deliverance at the sea, Moses and Israel sing — gratitude as communal song.",
    context: "The Song of the Sea is a classic biblical thanksgiving hymn after rescue.",
    application: "Some gratitude wants expression, not only private feeling.",
    takeaway: "Share one thanks out loud with someone who can receive it.",
    question: "What deliverance in your life still deserves a song?",
    acknowledgment: "Relief can open into praise.",
    keywords: ["song", "thanks", "deliverance", "praise", "gratitude"],
  },
  {
    id: "gratitude-lev-7-12",
    theme: "gratitude",
    themeLabel: "Gratitude",
    canonical: "Leviticus 7:12",
    url: "https://www.sefaria.org/Leviticus.7.12",
    text: "Leviticus describes a thanksgiving offering among peace offerings — ritualized gratitude.",
    context: "Sacrificial categories include thanksgiving as a distinct mode of approach.",
    application: "Making gratitude concrete (gift, words, ritual) can deepen it.",
    takeaway: "Turn a private thanks into one concrete gesture.",
    question: "How could your gratitude take a form others can feel?",
    acknowledgment: "Gratitude wants a body, not only a thought.",
    keywords: ["thanksgiving", "offering", "gratitude", "thanks"],
  },
  {
    id: "gratitude-gen-24-27",
    theme: "gratitude",
    themeLabel: "Gratitude",
    canonical: "Genesis 24:27",
    url: "https://www.sefaria.org/Genesis.24.27",
    text: "Abraham’s servant blesses God for steadfast kindness that guided his errand.",
    context: "A narrative blessing recognizes guidance in the search for Isaac’s partner.",
    application: "Noticing guidance mid-task can reframe ordinary work as accompanied.",
    takeaway: "Midway through a task, name one kindness that helped you get this far.",
    question: "Where has kindness already met you on the road?",
    acknowledgment: "Guidance often shows up in the middle of errands.",
    keywords: ["kindness", "bless", "guidance", "gratitude"],
  },
  // community (+4)
  {
    id: "community-exodus-19-6",
    theme: "community",
    themeLabel: "Community",
    canonical: "Exodus 19:6",
    url: "https://www.sefaria.org/Exodus.19.6",
    text: "Israel is called a kingdom of priests and a holy nation — identity framed communally.",
    context: "Covenant language at Sinai addresses a people, not only individuals.",
    application: "Spiritual identity in Torah is often woven through shared peoplehood.",
    takeaway: "Invest in one communal tie this week, even briefly.",
    question: "Which community helps you become who you mean to be?",
    acknowledgment: "Belonging can be a calling, not only a comfort.",
    keywords: ["nation", "people", "community", "holy", "together"],
  },
  {
    id: "community-num-11-10",
    theme: "community",
    themeLabel: "Community",
    canonical: "Numbers 11:10-15",
    url: "https://www.sefaria.org/Numbers.11.10",
    text: "Moses feels crushed by the people’s weeping and asks not to bear them alone.",
    context: "Communal complaint overwhelms a leader; the narrative validates the weight of shared life.",
    application: "Community is sustaining and also demanding — both truths can be named.",
    takeaway: "If community feels heavy, ask for help rather than disappearing.",
    question: "What support would make belonging sustainable?",
    acknowledgment: "Community can exhaust as well as nourish.",
    keywords: ["burden", "people", "alone", "community", "overwhelm"],
  },
  {
    id: "community-deut-31-12",
    theme: "community",
    themeLabel: "Community",
    canonical: "Deuteronomy 31:12",
    url: "https://www.sefaria.org/Deuteronomy.31.12",
    text: "The hakhel gathering includes men, women, children, and the stranger — a wide circle of hearing.",
    context: "Periodic public reading of Torah is framed as inclusive assembly.",
    application: "Learning communities are healthier when they make room for those at the margins.",
    takeaway: "Notice who is missing from the circles you help shape.",
    question: "Whose presence would make your community more complete?",
    acknowledgment: "A true assembly makes room.",
    keywords: ["assemble", "gather", "stranger", "community", "include"],
  },
  {
    id: "community-lev-25-35",
    theme: "community",
    themeLabel: "Community",
    canonical: "Leviticus 25:35",
    url: "https://www.sefaria.org/Leviticus.25.35",
    text: "If your kin falls into poverty, you are to support them so they can live beside you.",
    context: "Sabbatical/Jubilee ethics bind economic support to shared life.",
    application: "Community includes material solidarity, not only sentiment.",
    takeaway: "Offer one practical support that helps someone remain upright beside you.",
    question: "Who near you needs support that preserves dignity?",
    acknowledgment: "Belonging includes not letting people fall alone.",
    keywords: ["poor", "support", "kin", "community", "solidarity"],
  },
  // justice (+4)
  {
    id: "justice-exodus-23-6",
    theme: "justice",
    themeLabel: "Justice",
    canonical: "Exodus 23:6",
    url: "https://www.sefaria.org/Exodus.23.6",
    text: "Exodus warns not to pervert the justice due to the poor in their cause.",
    context: "Court ethics in the Covenant Code protect the vulnerable from distorted judgment.",
    application: "Fair process matters especially where power is uneven.",
    takeaway: "Check whether a process you influence treats the less powerful fairly.",
    question: "Where might convenience be bending fairness?",
    acknowledgment: "Justice can be quietly bent.",
    keywords: ["poor", "justice", "court", "fair", "pervert"],
  },
  {
    id: "justice-lev-19-15",
    theme: "justice",
    themeLabel: "Justice",
    canonical: "Leviticus 19:15",
    url: "https://www.sefaria.org/Leviticus.19.15",
    text: "Do not favor the poor or defer to the great; judge your fellow with righteousness.",
    context: "Holiness Code insists on impartial judgment — bias in either direction distorts justice.",
    application: "Fairness means resisting both pity-skew and status-skew.",
    takeaway: "Before deciding, ask what bias might be pulling you.",
    question: "Which face are you tempted to favor — and why?",
    acknowledgment: "Impartiality is harder than it sounds.",
    keywords: ["judge", "favor", "impartial", "righteousness", "justice"],
  },
  {
    id: "justice-deut-24-17",
    theme: "justice",
    themeLabel: "Justice",
    canonical: "Deuteronomy 24:17-18",
    url: "https://www.sefaria.org/Deuteronomy.24.17",
    text: "Do not pervert justice for the stranger or orphan; remember you were slaves in Egypt.",
    context: "Memory of vulnerability becomes a reason for protecting others’ justice.",
    application: "Personal history of vulnerability can fuel ethical solidarity.",
    takeaway: "Let a memory of your own vulnerability widen your fairness today.",
    question: "Whose justice are you positioned to protect?",
    acknowledgment: "Remembered vulnerability can become moral fuel.",
    keywords: ["stranger", "orphan", "justice", "egypt", "memory"],
  },
  {
    id: "justice-exodus-23-2",
    theme: "justice",
    themeLabel: "Justice",
    canonical: "Exodus 23:2",
    url: "https://www.sefaria.org/Exodus.23.2",
    text: "Do not follow a multitude to do evil — majority pressure is not moral permission.",
    context: "Judicial ethics warn against mob-tilted testimony and judgment.",
    application: "Crowds can normalize harm; conscience may need to stand apart.",
    takeaway: "If the group is rushing, pause and check the ethical cost.",
    question: "Where might majority momentum be asking you to abandon fairness?",
    acknowledgment: "Crowds can make wrong feel normal.",
    keywords: ["multitude", "majority", "peer pressure", "justice", "evil"],
  },
  // rest (+4)
  {
    id: "rest-gen-2-2",
    theme: "rest",
    themeLabel: "Rest",
    canonical: "Genesis 2:2-3",
    url: "https://www.sefaria.org/Genesis.2.2",
    text: "God ceases from work on the seventh day and blesses it — rest woven into creation’s rhythm.",
    context: "Creation’s climax is cessation and blessing, not only productivity.",
    application: "Rest can be sacred pattern, not leftover time.",
    takeaway: "Protect one unproductive hour as intentional cessation.",
    question: "What would it mean to bless a pause instead of resenting it?",
    acknowledgment: "Creation itself makes room for stopping.",
    keywords: ["seventh day", "ceased", "rest", "creation", "sabbath"],
  },
  {
    id: "rest-exodus-23-12",
    theme: "rest",
    themeLabel: "Rest",
    canonical: "Exodus 23:12",
    url: "https://www.sefaria.org/Exodus.23.12",
    text: "Six days you shall do your work, but on the seventh day you shall rest — so that ox, ass, and the stranger’s child may be refreshed.",
    context: "Sabbath rest extends to workers, animals, and dependents — rest as shared dignity.",
    application: "Your rest may also enable others’ refreshment.",
    takeaway: "Rest in a way that doesn’t quietly dump labor onto someone else.",
    question: "Whose rest is entangled with yours?",
    acknowledgment: "Rest is communal ethics, not only self-care.",
    keywords: ["rest", "refreshed", "worker", "sabbath", "ox"],
  },
  {
    id: "rest-lev-25-4",
    theme: "rest",
    themeLabel: "Rest",
    canonical: "Leviticus 25:4",
    url: "https://www.sefaria.org/Leviticus.25.4",
    text: "The land itself is to keep a sabbath — rest expands beyond human schedules to ecological rhythm.",
    context: "Sabbatical year law gives the land release from relentless cultivation.",
    application: "Systems and places, not only people, need cycles of release.",
    takeaway: "Give one overworked system in your life a deliberate fallow period.",
    question: "What have you been cultivating without rest?",
    acknowledgment: "Even land needs a sabbath.",
    keywords: ["sabbath of the land", "fallow", "rest", "release"],
  },
  {
    id: "rest-deut-5-14",
    theme: "rest",
    themeLabel: "Rest",
    canonical: "Deuteronomy 5:14",
    url: "https://www.sefaria.org/Deuteronomy.5.14",
    text: "Deuteronomy’s Sabbath commandment emphasizes rest for you, your household, your animals, and the stranger.",
    context: "The Decalogue in Deuteronomy links Sabbath to remembering liberation from Egypt.",
    application: "Rest can be an act of freedom from endless extraction.",
    takeaway: "Treat rest as freedom practice: stop extracting from yourself for a set time.",
    question: "What would freer rest look like this week?",
    acknowledgment: "Endless work can feel like a quieter Egypt.",
    keywords: ["sabbath", "rest", "household", "freedom", "stranger"],
  },
  // speech (+3)
  {
    id: "speech-exodus-23-1",
    theme: "speech",
    themeLabel: "Speech and gossip",
    canonical: "Exodus 23:1",
    url: "https://www.sefaria.org/Exodus.23.1",
    text: "Do not carry a false report — speech ethics begin with refusing to traffic in untrue words.",
    context: "Covenant Code court ethics guard testimony and rumor.",
    application: "Passing along an unchecked story can make you a carrier of harm.",
    takeaway: "Before forwarding a claim, verify or stay silent.",
    question: "What report are you tempted to carry without checking?",
    acknowledgment: "False reports travel lightly and land heavily.",
    keywords: ["false report", "rumor", "speech", "gossip", "witness"],
  },
  {
    id: "speech-deut-19-15",
    theme: "speech",
    themeLabel: "Speech and gossip",
    canonical: "Deuteronomy 19:15",
    url: "https://www.sefaria.org/Deuteronomy.19.15",
    text: "A single witness is not enough to convict — truth-claims about people require careful corroboration.",
    context: "Judicial procedure protects against solitary accusation.",
    application: "Be slow to treat one heated account as the whole truth about someone.",
    takeaway: "Seek a second perspective before concluding about a person’s character.",
    question: "Where have you let one voice decide the whole story?",
    acknowledgment: "One witness can feel convincing — and still be incomplete.",
    keywords: ["witness", "accusation", "speech", "truth", "corroborate"],
  },
  {
    id: "speech-lev-19-11",
    theme: "speech",
    themeLabel: "Speech and gossip",
    canonical: "Leviticus 19:11",
    url: "https://www.sefaria.org/Leviticus.19.11",
    text: "Do not deal falsely or lie to one another — truthfulness is part of holy community life.",
    context: "Holiness Code pairs interpersonal honesty with other ethical demands.",
    application: "Ordinary honesty is spiritual practice, not only manners.",
    takeaway: "Choose one conversation today for cleaner honesty without cruelty.",
    question: "Where is a soft falsehood costing trust?",
    acknowledgment: "Small untruths still shape a community.",
    keywords: ["lie", "false", "honesty", "speech", "truth"],
  },
  // uncertainty (+4)
  {
    id: "uncertainty-gen-12-1",
    theme: "uncertainty",
    themeLabel: "Uncertainty",
    canonical: "Genesis 12:1",
    url: "https://www.sefaria.org/Genesis.12.1",
    text: "Abram is told to go to a land that will be shown — vocation begins before the map is complete.",
    context: "The call of Abram launches a journey whose destination is disclosed in stages.",
    application: "Faithful movement can precede full clarity.",
    takeaway: "Take the next indicated step without demanding the whole itinerary.",
    question: "What is the next step you already know, even if the destination is incomplete?",
    acknowledgment: "Sometimes you go before you see.",
    keywords: ["go", "land", "uncertain", "call", "journey"],
  },
  {
    id: "uncertainty-exodus-16-4",
    theme: "uncertainty",
    themeLabel: "Uncertainty",
    canonical: "Exodus 16:4",
    url: "https://www.sefaria.org/Exodus.16.4",
    text: "Manna is given day by day — provision arrives in portions that discourage anxious stockpiling.",
    context: "Wilderness food becomes a training in daily trust.",
    application: "Not every need must be solved for the whole year today.",
    takeaway: "Ask what is enough for today, and do that well.",
    question: "What future anxiety can you set down until tomorrow?",
    acknowledgment: "Daily bread can be a spiritual curriculum.",
    keywords: ["manna", "daily", "enough", "anxiety", "trust"],
  },
  {
    id: "uncertainty-deut-29-28",
    theme: "uncertainty",
    themeLabel: "Uncertainty",
    canonical: "Deuteronomy 29:28",
    url: "https://www.sefaria.org/Deuteronomy.29.28",
    text: "The secret things belong to God, while revealed things belong to us and our children to do.",
    context: "Covenant rhetoric distinguishes mystery from actionable revelation.",
    application: "Focus on revealed responsibilities rather than unknowable outcomes.",
    takeaway: "List what is yours to do; release what is not yours to know.",
    question: "What revealed duty is getting lost in speculation?",
    acknowledgment: "Not everything hidden needs to be solved by you.",
    keywords: ["secret", "revealed", "uncertain", "mystery", "responsibility"],
  },
  {
    id: "uncertainty-num-9-15",
    theme: "uncertainty",
    themeLabel: "Uncertainty",
    canonical: "Numbers 9:17-23",
    url: "https://www.sefaria.org/Numbers.9.17",
    text: "Israel camps and journeys by the cloud’s staying or lifting — movement timed to guidance, not impatience.",
    context: "Wilderness itinerary is narrated as responsive to divine signal.",
    application: "Discernment sometimes means waiting for a clear go, not forcing motion.",
    takeaway: "If the signal isn’t clear, choose watchful waiting over restless thrashing.",
    question: "Are you moving because it’s time — or because waiting feels unbearable?",
    acknowledgment: "Waiting for clarity can feel like standing still in a desert.",
    keywords: ["cloud", "journey", "wait", "guidance", "uncertain"],
  },
  // learning (+3)
  {
    id: "learning-deut-6-7",
    theme: "learning",
    themeLabel: "Learning",
    canonical: "Deuteronomy 6:7",
    url: "https://www.sefaria.org/Deuteronomy.6.7",
    text: "You shall teach them diligently to your children and speak of them at home and on the way.",
    context: "The Shema passage frames teaching as continuous, embedded in daily life.",
    application: "Learning thrives when woven into ordinary rhythms, not only special events.",
    takeaway: "Choose one daily moment to revisit a teaching out loud.",
    question: "Where could learning live in your ordinary schedule?",
    acknowledgment: "Wisdom wants a place in the day’s path.",
    keywords: ["teach", "children", "shema", "learning", "diligent"],
  },
  {
    id: "learning-deut-31-19",
    theme: "learning",
    themeLabel: "Learning",
    canonical: "Deuteronomy 31:19",
    url: "https://www.sefaria.org/Deuteronomy.31.19",
    text: "Write this song and teach it — memory is strengthened through composition and instruction.",
    context: "Moses is commanded to transmit a song as witness for future generations.",
    application: "Teaching others can deepen what we ourselves remember.",
    takeaway: "Explain one insight to someone else in simple words.",
    question: "What have you learned that is ready to be taught?",
    acknowledgment: "Teaching seals learning.",
    keywords: ["write", "teach", "song", "memory", "learning"],
  },
  {
    id: "learning-exodus-13-8",
    theme: "learning",
    themeLabel: "Learning",
    canonical: "Exodus 13:8",
    url: "https://www.sefaria.org/Exodus.13.8",
    text: "You shall tell your child on that day — story becomes pedagogy.",
    context: "Passover instruction turns historical memory into intergenerational teaching.",
    application: "Personal and communal stories can be classrooms.",
    takeaway: "Share one formative story with someone younger or newer.",
    question: "Which story from your life still teaches?",
    acknowledgment: "Stories carry Torah into the next generation.",
    keywords: ["tell", "child", "story", "passover", "learning"],
  },
  // generosity (+3)
  {
    id: "generosity-lev-19-9",
    theme: "generosity",
    themeLabel: "Generosity",
    canonical: "Leviticus 19:9-10",
    url: "https://www.sefaria.org/Leviticus.19.9",
    text: "Leave the gleanings of field and vineyard for the poor and the stranger — generosity built into harvest.",
    context: "Agricultural gifts institutionalize access for the vulnerable.",
    application: "Design systems that leave margin for others, not only occasional charity.",
    takeaway: "Build one intentional margin into your budget or time for others’ access.",
    question: "What “gleanings” could your abundance leave behind?",
    acknowledgment: "Generosity can be designed, not only improvised.",
    keywords: ["gleanings", "poor", "stranger", "harvest", "generosity"],
  },
  {
    id: "generosity-deut-14-28",
    theme: "generosity",
    themeLabel: "Generosity",
    canonical: "Deuteronomy 14:28-29",
    url: "https://www.sefaria.org/Deuteronomy.14.28",
    text: "A triennial tithe supports Levite, stranger, orphan, and widow so they may eat and be satisfied.",
    context: "Tithe structures redistribute toward those without land inheritance.",
    application: "Regular giving can be more reliable than spontaneous impulse alone.",
    takeaway: "Set a recurring gift sized to what you can sustain.",
    question: "Who becomes satisfied because you give regularly?",
    acknowledgment: "Steady generosity feeds people better than rare spectacle.",
    keywords: ["tithe", "orphan", "widow", "stranger", "give"],
  },
  {
    id: "generosity-exodus-25-2",
    theme: "generosity",
    themeLabel: "Generosity",
    canonical: "Exodus 25:2",
    url: "https://www.sefaria.org/Exodus.25.2",
    text: "Take a gift from everyone whose heart moves them — generosity joined to willing heart.",
    context: "Tabernacle contributions are framed as freewill offerings stirred by heart.",
    application: "The spirit of willingness matters alongside the gift.",
    takeaway: "Give where your heart is genuinely moved, not only where guilt pushes.",
    question: "Where is your heart already leaning toward generosity?",
    acknowledgment: "Willing gifts feel different from pressured ones.",
    keywords: ["offering", "heart", "gift", "willing", "generosity"],
  },
  // technology (+4)
  {
    id: "technology-exodus-31-1",
    theme: "technology",
    themeLabel: "Technology and responsibility",
    canonical: "Exodus 31:1-5",
    url: "https://www.sefaria.org/Exodus.31.1",
    text: "Bezalel is filled with skill for craftsmanship — artistry and tool-skill presented as inspired responsibility.",
    context: "Tabernacle artisanship treats technical skill as vocation under sacred purpose.",
    application: "Making and tools can serve dignity and beauty when guided by purpose.",
    takeaway: "Ask what purpose your next tool or project is meant to serve.",
    question: "Is your craft serving a worthy end, or only capability?",
    acknowledgment: "Skill is a trust.",
    keywords: ["craft", "skill", "bezalel", "tool", "workmanship"],
  },
  {
    id: "technology-exodus-20-4",
    theme: "technology",
    themeLabel: "Technology and responsibility",
    canonical: "Exodus 20:4",
    url: "https://www.sefaria.org/Exodus.20.4",
    text: "Do not make a graven image — a warning about crafted representations that can capture devotion wrongly.",
    context: "The Decalogue’s image prohibition targets idolatrous representation, not all art.",
    application: "Powerful images and tools can become objects of misplaced trust.",
    takeaway: "Notice where a tool or feed is asking for devotion it shouldn’t have.",
    question: "What technology is quietly claiming your worshipful attention?",
    acknowledgment: "Tools can become idols without looking like statues.",
    keywords: ["image", "idol", "graven", "technology", "attention"],
  },
  {
    id: "technology-deut-27-18",
    theme: "technology",
    themeLabel: "Technology and responsibility",
    canonical: "Deuteronomy 27:18",
    url: "https://www.sefaria.org/Deuteronomy.27.18",
    text: "Cursed is one who misleads the blind on the way — harming the vulnerable through deceptive guidance.",
    context: "Covenant curses include social harms against those who cannot see the danger.",
    application: "Misleading interfaces, advice, or systems can be a modern form of misdirection.",
    takeaway: "If you design or recommend a path, check it for hidden traps.",
    question: "Who might be misled by a tool or word you influence?",
    acknowledgment: "Misleading the vulnerable is a grave betrayal.",
    keywords: ["blind", "mislead", "stumbling", "guidance", "technology"],
  },
  {
    id: "technology-gen-11-4",
    theme: "technology",
    themeLabel: "Technology and responsibility",
    canonical: "Genesis 11:4",
    url: "https://www.sefaria.org/Genesis.11.4",
    text: "Babel’s builders seek a tower and a name — ambition through collective making without ethical limit.",
    context: "The Babel narrative critiques concentrated human projects that reach beyond right relation.",
    application: "Capability and coordination are not themselves virtue.",
    takeaway: "Before scaling a project, ask what good it serves beyond reputation.",
    question: "Is your build about a name — or about a good?",
    acknowledgment: "Ambitious making needs moral brakes.",
    keywords: ["babel", "tower", "ambition", "build", "technology"],
  },
  {
    id: "forgiveness-gen-50-17b",
    theme: "forgiveness",
    themeLabel: "Forgiveness",
    canonical: "Genesis 50:17",
    url: "https://www.sefaria.org/Genesis.50.17",
    text: "Joseph’s brothers plead for forgiveness for the wrong they did; the story holds fear, request, and mercy together.",
    context: "Forgiveness appears at the end of a long narrative of harm and providence.",
    application: "Forgiveness can be requested and considered without erasing history.",
    takeaway: "If you seek forgiveness, name the wrong specifically.",
    question: "What wrong needs naming before forgiveness can be real?",
    acknowledgment: "Asking forgiveness takes courage.",
    keywords: ["forgive", "forgiveness", "pardon", "mercy", "joseph"],
  },
  {
    id: "forgiveness-exodus-34-7",
    theme: "forgiveness",
    themeLabel: "Forgiveness",
    canonical: "Exodus 34:6-7",
    url: "https://www.sefaria.org/Exodus.34.6",
    text: "God is described as forgiving iniquity while also not clearing the guilty — mercy and accountability held together.",
    context: "The attributes of Exodus 34 shape later Jewish theology of divine mercy.",
    application: "Forgiveness need not mean pretending consequences disappear.",
    takeaway: "Hold mercy and accountability in the same conversation.",
    question: "Where do you need mercy — and where do you still need accountability?",
    acknowledgment: "Mercy and truth can share a room.",
    keywords: ["forgiving", "iniquity", "mercy", "accountability"],
  },
  {
    id: "forgiveness-num-14-19",
    theme: "forgiveness",
    themeLabel: "Forgiveness",
    canonical: "Numbers 14:19-20",
    url: "https://www.sefaria.org/Numbers.14.19",
    text: "Moses asks God to pardon the people’s iniquity; pardon is granted according to steadfast love.",
    context: "Intercession after the spies crisis links leadership, plea, and pardon.",
    application: "Sometimes forgiveness is sought on behalf of a community, not only the self.",
    takeaway: "Ask for pardon with honesty about the harm.",
    question: "Whose well-being depends on a pardon larger than one private feeling?",
    acknowledgment: "Communities need pardon too.",
    keywords: ["pardon", "forgive", "steadfast love", "people"],
  },
  {
    id: "anger-gen-4-5",
    theme: "anger",
    themeLabel: "Anger",
    canonical: "Genesis 4:5-7",
    url: "https://www.sefaria.org/Genesis.4.5",
    text: "Cain’s anger and fallen face receive a warning that sin crouches at the door — anger as a threshold moment.",
    context: "The Cain narrative treats anger as morally charged before violence.",
    application: "Noticing anger early can interrupt harm.",
    takeaway: "When your face falls, name the anger before it chooses for you.",
    question: "What is crouching at the door of your anger right now?",
    acknowledgment: "Anger often arrives with a warning.",
    keywords: ["anger", "cain", "wrath", "face fell", "rage"],
  },
  {
    id: "anger-exodus-32-19",
    theme: "anger",
    themeLabel: "Anger",
    canonical: "Exodus 32:19",
    url: "https://www.sefaria.org/Exodus.32.19",
    text: "Moses’ anger burns when he sees the calf — righteous anger appears in Torah, and so do its costs.",
    context: "The golden calf episode includes prophetic rage and broken tablets.",
    application: "Anger at injustice can be real; how it is expressed still matters.",
    takeaway: "If anger is righteous, still choose an expression that doesn’t multiply harm.",
    question: "What is your anger protecting — and what might it break?",
    acknowledgment: "Some fires are lit by love of the good.",
    keywords: ["anger burned", "moses", "calf", "rage", "tablets"],
  },
  {
    id: "anger-lev-19-18-grudge",
    theme: "anger",
    themeLabel: "Anger",
    canonical: "Leviticus 19:18",
    url: "https://www.sefaria.org/Leviticus.19.18",
    text: "Do not take vengeance or bear a grudge — anger’s long afterlife is limited by Torah ethics.",
    context: "Neighbor-love is paired with restraints on revenge and grudge-bearing.",
    application: "Releasing a grudge is different from denying that harm happened.",
    takeaway: "Name the hurt, then ask what carrying the grudge is costing you.",
    question: "What grudge is asking to be set down without rewriting history?",
    acknowledgment: "Grudges can feel like armor and become a weight.",
    keywords: ["grudge", "vengeance", "anger", "neighbor"],
  },
  {
    id: "humility-num-12-3b",
    theme: "humility",
    themeLabel: "Humility",
    canonical: "Numbers 12:3",
    url: "https://www.sefaria.org/Numbers.12.3",
    text: "Moses is called very humble, more than anyone on earth — humility as leadership virtue.",
    context: "The narrator’s aside appears amid sibling challenge to Moses’ unique role.",
    application: "Humility can coexist with responsibility.",
    takeaway: "Practice one act of stepping back so another voice can be heard.",
    question: "Where could humility make your leadership clearer?",
    acknowledgment: "Humility is not the same as disappearance.",
    keywords: ["humble", "humility", "moses", "ego"],
  },
  {
    id: "humility-deut-8-14",
    theme: "humility",
    themeLabel: "Humility",
    canonical: "Deuteronomy 8:14",
    url: "https://www.sefaria.org/Deuteronomy.8.14",
    text: "Beware lest your heart be lifted up when you have plenty — success can erode humility.",
    context: "Moses warns Israel that prosperity may produce forgetfulness and pride.",
    application: "Abundance needs practices that keep the heart from swelling.",
    takeaway: "In a success, thank someone who helped make it possible.",
    question: "What success is quietly lifting your heart?",
    acknowledgment: "Plenty can make us forget how we arrived.",
    keywords: ["heart lifted", "pride", "humility", "prosperity"],
  },
  {
    id: "humility-gen-18-27",
    theme: "humility",
    themeLabel: "Humility",
    canonical: "Genesis 18:27",
    url: "https://www.sefaria.org/Genesis.18.27",
    text: "Abraham approaches argument with God while calling himself dust and ashes — boldness with humility.",
    context: "Abraham’s intercession for Sodom pairs moral courage with humility language.",
    application: "You can advocate firmly without self-importance.",
    takeaway: "Speak your conviction, then check your ego at the door.",
    question: "Can your next hard ask hold both courage and dust-and-ashes honesty?",
    acknowledgment: "The boldest prayers can still be humble.",
    keywords: ["dust", "ashes", "abraham", "humility", "intercede"],
  },
  {
    id: "hospitality-gen-18-1",
    theme: "hospitality",
    themeLabel: "Hospitality",
    canonical: "Genesis 18:1-8",
    url: "https://www.sefaria.org/Genesis.18.1",
    text: "Abraham runs to welcome strangers with water, rest, and a meal — hospitality as eager care.",
    context: "Classical Jewish ethics treat Abraham’s welcoming as a model of hachnasat orchim.",
    application: "Welcome can be active: notice, approach, refresh.",
    takeaway: "Offer one concrete comfort to a guest or newcomer today.",
    question: "Who near you needs welcome more than advice?",
    acknowledgment: "Strangers become guests through welcome.",
    keywords: ["welcome", "stranger", "guest", "hospitality", "abraham"],
  },
  {
    id: "hospitality-lev-19-34",
    theme: "hospitality",
    themeLabel: "Hospitality",
    canonical: "Leviticus 19:34",
    url: "https://www.sefaria.org/Leviticus.19.34",
    text: "The stranger who dwells with you shall be as a citizen; love the stranger as yourself.",
    context: "Holiness Code extends neighbor ethics to the resident stranger.",
    application: "Hospitality includes structural belonging, not only a meal.",
    takeaway: "Help one outsider feel like an insider in a space you influence.",
    question: "Who is still treated as temporary in your community?",
    acknowledgment: "Love of the stranger is Torah, not optional niceness.",
    keywords: ["stranger", "sojourner", "love", "hospitality", "citizen"],
  },
  {
    id: "hospitality-deut-10-19",
    theme: "hospitality",
    themeLabel: "Hospitality",
    canonical: "Deuteronomy 10:19",
    url: "https://www.sefaria.org/Deuteronomy.10.19",
    text: "Love the stranger, for you were strangers in Egypt — memory fuels hospitality.",
    context: "Israel’s own strangerhood becomes the reason for ethical welcome.",
    application: "Remembered outsider experience can soften how we treat newcomers.",
    takeaway: "Recall a time you were new — then act from that memory.",
    question: "How did it feel to be the stranger — and who feels that now?",
    acknowledgment: "We were strangers once.",
    keywords: ["stranger", "egypt", "love", "hospitality", "memory"],
  },
  {
    id: "family-exodus-20-12",
    theme: "family",
    themeLabel: "Family",
    canonical: "Exodus 20:12",
    url: "https://www.sefaria.org/Exodus.20.12",
    text: "Honor your father and your mother — family ethics appear among the foundational commandments.",
    context: "The Decalogue places parental honor between God-facing and interpersonal commands.",
    application: "Honor can mean respect and care suited to real relationships, which are often complex.",
    takeaway: "Choose one honoring act that fits the relationship you actually have.",
    question: "What would honor look like without pretending the relationship is simple?",
    acknowledgment: "Family commandments meet complicated lives.",
    keywords: ["honor", "father", "mother", "parents", "family"],
  },
  {
    id: "family-gen-45-1",
    theme: "family",
    themeLabel: "Family",
    canonical: "Genesis 45:1-5",
    url: "https://www.sefaria.org/Genesis.45.1",
    text: "Joseph reveals himself to his brothers with weeping — family repair includes emotion, truth, and reframing.",
    context: "A climactic family recognition scene after years of estrangement.",
    application: "Family healing may need both honesty and carefully timed disclosure.",
    takeaway: "If a family truth needs telling, prepare the setting with care.",
    question: "What family truth is waiting for the right room?",
    acknowledgment: "Family reunions can shake us open.",
    keywords: ["brothers", "family", "reveal", "weep", "joseph"],
  },
  {
    id: "family-deut-6-7b",
    theme: "family",
    themeLabel: "Family",
    canonical: "Deuteronomy 6:7",
    url: "https://www.sefaria.org/Deuteronomy.6.7",
    text: "Teach them diligently to your children — family as a primary school of meaning.",
    context: "Shema instruction embeds teaching in household life.",
    application: "Families transmit values through repeated conversation, not only rules.",
    takeaway: "Share one value out loud with someone in your household.",
    question: "What are you teaching by what you repeat at home?",
    acknowledgment: "Homes are classrooms whether we intend them to be or not.",
    keywords: ["children", "teach", "home", "family", "household"],
  },
  {
    id: "work-exodus-20-9",
    theme: "work",
    themeLabel: "Work",
    canonical: "Exodus 20:9-10",
    url: "https://www.sefaria.org/Exodus.20.9",
    text: "Six days shall you labor and do all your work, but the seventh day is a sabbath — work and stoppage paired.",
    context: "The Decalogue frames labor as real and limited.",
    application: "Good work includes knowing when to stop.",
    takeaway: "Do today’s work fully, then stop without apology.",
    question: "Where is work spilling past its rightful six days?",
    acknowledgment: "Work is holy — and so is its limit.",
    keywords: ["labor", "work", "six days", "job", "sabbath"],
  },
  {
    id: "work-deut-24-14",
    theme: "work",
    themeLabel: "Work",
    canonical: "Deuteronomy 24:14-15",
    url: "https://www.sefaria.org/Deuteronomy.24.14",
    text: "Do not oppress a hired worker; pay wages on the day — labor ethics protect timely livelihood.",
    context: "Deuteronomy guards workers, especially the poor and vulnerable.",
    application: "Fair work includes fair and prompt compensation.",
    takeaway: "If you control payment or credit, remove needless delay.",
    question: "Whose livelihood depends on your timely fairness?",
    acknowledgment: "A day’s wage can be someone’s whole margin.",
    keywords: ["wage", "hire", "worker", "oppress", "work"],
  },
  {
    id: "work-gen-2-15b",
    theme: "work",
    themeLabel: "Work",
    canonical: "Genesis 2:15",
    url: "https://www.sefaria.org/Genesis.2.15",
    text: "The human is placed in the garden to till it and keep it — work as tending, not only extracting.",
    context: "Eden work is framed as service and guardianship.",
    application: "Meaningful work can include caretaking of what is entrusted.",
    takeaway: "Name one part of your work that is really tending.",
    question: "What are you keeping, not just using?",
    acknowledgment: "Some work is gardening the world.",
    keywords: ["till", "keep", "garden", "work", "tend"],
  },
  {
    id: "hope-gen-9-13",
    theme: "hope",
    themeLabel: "Hope",
    canonical: "Genesis 9:13-16",
    url: "https://www.sefaria.org/Genesis.9.13",
    text: "The rainbow is set as a sign of covenant after the flood — hope marked in the sky after catastrophe.",
    context: "Post-flood covenant reassures continuity of seasons and life.",
    application: "Hope can be covenanted: a promise that ruin is not the final word.",
    takeaway: "Name one sign that life is continuing after your hard season.",
    question: "Where is a rainbow already visible, even faintly?",
    acknowledgment: "After floodwaters, signs still matter.",
    keywords: ["rainbow", "covenant", "hope", "flood", "sign"],
  },
  {
    id: "hope-exodus-2-23",
    theme: "hope",
    themeLabel: "Hope",
    canonical: "Exodus 2:23-25",
    url: "https://www.sefaria.org/Exodus.2.23",
    text: "Israel groans under bondage; God hears, remembers, sees, and knows — hope begins in being heard.",
    context: "The Exodus turns when suffering is acknowledged.",
    application: "Hope grows when pain is witnessed, not minimized.",
    takeaway: "Tell one trusted person the true weight of what you carry.",
    question: "Who can hear you without rushing to fix you?",
    acknowledgment: "Being heard is already a beginning.",
    keywords: ["groan", "bondage", "heard", "hope", "remember"],
  },
  {
    id: "hope-deut-30-3",
    theme: "hope",
    themeLabel: "Hope",
    canonical: "Deuteronomy 30:3-4",
    url: "https://www.sefaria.org/Deuteronomy.30.3",
    text: "Even if driven to the ends of heaven, return and gathering remain possible — hope beyond exile.",
    context: "Deuteronomy’s return passages imagine restoration after dispersion.",
    application: "Distance — geographic or spiritual — need not be final.",
    takeaway: "Take one step of return toward what matters most.",
    question: "What return is still possible for you?",
    acknowledgment: "Exile is not always the end of the story.",
    keywords: ["return", "gather", "exile", "hope", "restore"],
  },
  {
    id: "truth-exodus-23-7",
    theme: "truth",
    themeLabel: "Truth",
    canonical: "Exodus 23:7",
    url: "https://www.sefaria.org/Exodus.23.7",
    text: "Keep far from a false matter — truthfulness includes distance from shady claims.",
    context: "Judicial ethics demand separation from falsehood.",
    application: "Integrity sometimes means refusing proximity to a convenient lie.",
    takeaway: "Step back from one conversation that thrives on distortion.",
    question: "What false matter are you standing too near?",
    acknowledgment: "Distance from falsehood is an active choice.",
    keywords: ["false", "truth", "lie", "matter", "honest"],
  },
  {
    id: "truth-deut-16-20b",
    theme: "truth",
    themeLabel: "Truth",
    canonical: "Deuteronomy 16:20",
    url: "https://www.sefaria.org/Deuteronomy.16.20",
    text: "Justice, justice shall you pursue — truth-seeking tied to relentless fairness.",
    context: "Judicial appointment and integrity frame this famous charge.",
    application: "Pursuing what is true and fair may require repetition and care.",
    takeaway: "Correct one inaccuracy you have been letting stand.",
    question: "Where does truth need another pursuit?",
    acknowledgment: "Truth often needs pursuing, not assuming.",
    keywords: ["justice", "truth", "pursue", "fair"],
  },
  {
    id: "truth-lev-19-11b",
    theme: "truth",
    themeLabel: "Truth",
    canonical: "Leviticus 19:11",
    url: "https://www.sefaria.org/Leviticus.19.11",
    text: "Do not steal, deal falsely, or lie to one another — truth as communal fabric.",
    context: "Interpersonal honesty appears among holiness demands.",
    application: "Communities fray when small lies become normal.",
    takeaway: "Replace one soft falsehood with a careful truth.",
    question: "Which relationship needs cleaner truth from you?",
    acknowledgment: "Truth-telling is community care.",
    keywords: ["lie", "false", "truth", "honest", "steal"],
  },
  {
    id: "joy-deut-16-14",
    theme: "joy",
    themeLabel: "Joy",
    canonical: "Deuteronomy 16:14-15",
    url: "https://www.sefaria.org/Deuteronomy.16.14",
    text: "You shall rejoice in your festival — you, your household, and the stranger — joy as shared obligation.",
    context: "Festival law includes commanded rejoicing with an inclusive circle.",
    application: "Joy can be practiced and shared, not only privately felt.",
    takeaway: "Plan one small joy and invite someone into it.",
    question: "Whose joy could expand if you opened the circle?",
    acknowledgment: "Joy is allowed — even commanded — in season.",
    keywords: ["rejoice", "joy", "festival", "glad"],
  },
  {
    id: "joy-deut-26-11",
    theme: "joy",
    themeLabel: "Joy",
    canonical: "Deuteronomy 26:11",
    url: "https://www.sefaria.org/Deuteronomy.26.11",
    text: "You shall rejoice in all the good that has been given you and your household.",
    context: "First-fruits declaration ends in shared rejoicing.",
    application: "Noticing good received can become communal gladness.",
    takeaway: "Name one good aloud and celebrate it without irony.",
    question: "What good have you been too busy to enjoy?",
    acknowledgment: "Good deserves rejoicing, not only managing.",
    keywords: ["rejoice", "good", "joy", "household"],
  },
  {
    id: "joy-exodus-15-20",
    theme: "joy",
    themeLabel: "Joy",
    canonical: "Exodus 15:20-21",
    url: "https://www.sefaria.org/Exodus.15.20",
    text: "Miriam leads the women with timbrels and dance after deliverance — embodied communal joy.",
    context: "Song of the Sea includes Miriam’s responsive celebration.",
    application: "Bodies and communities can carry joy when words are not enough.",
    takeaway: "Let joy move — music, walk, dance, or laughter — not only thought.",
    question: "How does your body want to mark a gladness?",
    acknowledgment: "Some thanks need drums.",
    keywords: ["miriam", "dance", "joy", "song", "timbrel"],
  },
  {
    id: "stewardship-gen-2-15c",
    theme: "stewardship",
    themeLabel: "Stewardship",
    canonical: "Genesis 2:15",
    url: "https://www.sefaria.org/Genesis.2.15",
    text: "Till and keep the garden — human vocation includes cultivation and protection.",
    context: "Eden charge frames humans as caretakers of place.",
    application: "Environmental care can be read as keeping what we did not invent.",
    takeaway: "Choose one keeping act: reduce waste, plant, repair, or protect a place.",
    question: "What garden — literal or metaphorical — is yours to keep?",
    acknowledgment: "The earth is not only raw material.",
    keywords: ["garden", "keep", "earth", "environment", "steward"],
  },
  {
    id: "stewardship-deut-20-19",
    theme: "stewardship",
    themeLabel: "Stewardship",
    canonical: "Deuteronomy 20:19",
    url: "https://www.sefaria.org/Deuteronomy.20.19",
    text: "Even in siege, fruit trees are not to be destroyed — restraint toward living resources.",
    context: "Wartime law limits scorched-earth destruction of food trees.",
    application: "Short-term urgency does not justify every destruction of what sustains life.",
    takeaway: "Refuse one convenience that casually destroys something living or lasting.",
    question: "What living good are you tempted to cut down for speed?",
    acknowledgment: "Even conflict has ecological ethics in Torah.",
    keywords: ["tree", "destroy", "fruit", "earth", "stewardship"],
  },
  {
    id: "stewardship-deut-22-6",
    theme: "stewardship",
    themeLabel: "Stewardship",
    canonical: "Deuteronomy 22:6-7",
    url: "https://www.sefaria.org/Deuteronomy.22.6",
    text: "If you find a bird’s nest, do not take the mother with the young — compassion extends to animals.",
    context: "A classic Torah law of animal compassion and restraint.",
    application: "Care for creatures can interrupt extractive habit.",
    takeaway: "Practice one kindness toward an animal or habitat this week.",
    question: "Where can compassion reach beyond the human circle?",
    acknowledgment: "Torah’s concern is wider than our species alone.",
    keywords: ["bird", "nest", "animal", "compassion", "stewardship"],
  },
];

export const DRAFT_TEACHINGS: Teaching[] = SEEDS.map(draft);
