/**
 * Everyday-language expansions for Torah retrieval.
 * These are retrieval aids, not claims that Torok “understands” Torah.
 */
export const QUERY_SYNONYMS: Record<string, string[]> = {
  coworker: ["neighbor", "fellow", "brother", "companion", "strife", "peace"],
  colleague: ["neighbor", "fellow", "brother"],
  boss: ["master", "authority", "judge", "rule"],
  argument: ["strife", "contend", "quarrel", "rebuke", "anger"],
  conflict: ["strife", "enemy", "peace", "neighbor"],
  anger: ["wrath", "fierce", "hot", "anger", "fury"],
  gossip: ["talebearer", "slander", "whisper", "false report"],
  speech: ["mouth", "lips", "tongue", "word", "speak"],
  patience: ["slow to anger", "longsuffering", "wait", "endure"],
  apology: ["confess", "return", "guilt", "sin", "forgive"],
  repair: ["restore", "return", "make amends", "guilt offering"],
  leadership: ["judge", "elder", "king", "rule", "appoint"],
  courage: ["fear not", "be strong", "dismayed", "brave"],
  gratitude: ["thank", "bless", "praise", "give thanks"],
  community: ["congregation", "assembly", "people", "camp"],
  justice: ["justice", "judgment", "righteous", "fair", "oppress"],
  rest: ["sabbath", "seventh day", "rest", "cease"],
  uncertainty: ["fear not", "trust", "way", "path", "choose"],
  learning: ["teach", "statute", "commandment", "hear", "remember"],
  generosity: ["poor", "needy", "open hand", "gift", "tithe"],
  technology: ["tool", "image", "craft", "work", "stumbling"],
  ai: ["image", "craft", "workmanship", "stumbling block"],
  family: ["father", "mother", "son", "daughter", "brother", "house"],
  stranger: ["stranger", "sojourner", "foreigner", "alien"],
  hospitality: ["stranger", "sojourner", "bread", "welcome"],
  money: ["silver", "debt", "interest", "poor", "wealth"],
  work: ["labor", "work", "six days", "hire", "wage"],
  envy: ["covet", "jealous", "grudge"],
  humility: ["humble", "meek", "dust", "lowly"],
  forgiveness: ["forgive", "pardon", "mercy", "iniquity"],
  hope: ["hope", "wait", "trust", "deliver"],
  truth: ["truth", "false", "witness", "honest"],
  power: ["rule", "authority", "oppress", "mighty"],
  joy: ["joy", "rejoice", "glad", "feast"],
  loss: ["mourn", "weep", "bereave", "death"],
  animal: ["ox", "ass", "cattle", "beast", "bird"],
  earth: ["land", "earth", "field", "tree", "fruit"],
  purpose: ["covenant", "choose", "life", "blessing"],
  change: ["return", "new", "heart", "turn"],
  listening: ["hear", "hearken", "ears", "listen"],
  dignity: ["image", "neighbor", "honor", "respect"],
  rebuke: ["rebuke", "reprove", "warn"],
  peace: ["peace", "shalom"],
  neighbor: ["neighbor", "fellow", "brother"],
};

export const THEME_TORAH_HINTS: Record<string, string[]> = {
  patience: ["slow to anger", "wait", "endure", "long"],
  repair: ["confess", "guilt", "return", "sin offering"],
  relationships: ["neighbor", "brother", "love", "peace", "strife"],
  leadership: ["judge", "elder", "appoint", "rule"],
  courage: ["fear not", "be strong", "dismayed"],
  gratitude: ["bless the lord", "thank", "praise"],
  community: ["congregation", "assembly", "camp"],
  justice: ["justice", "judgment", "oppress", "widow", "orphan"],
  rest: ["sabbath", "seventh day", "rest"],
  speech: ["false witness", "talebearer", "mouth", "lips"],
  uncertainty: ["fear not", "choose life", "way"],
  learning: ["teach", "statutes", "commandments", "hear o israel"],
  generosity: ["poor", "needy", "open thine hand", "tithe"],
  technology: ["graven image", "molten", "craft", "workmanship"],
};
